"""Full portable HTML integration tests; synthetic games only. pip install playwright"""
from pathlib import Path
import json, os, re, time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'review-test-output';OUT.mkdir(exist_ok=True)
html=(ROOT/'index.html').read_text();fixture=json.loads((ROOT/'review/fixture.json').read_text())
checks=[];errors=[]
def check(name,condition=True):
 assert condition,name
 checks.append(name);print('PASS '+name,flush=True)
def state(page):return page.evaluate('GomokuReview.state()')
with sync_playwright() as p:
 executable=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium')
 b=p.chromium.launch(executable_path=executable if Path(executable).exists() else None,headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':1440,'height':1000});page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(os.environ['REVIEW_URL'],wait_until='domcontentloaded',timeout=30000) if os.environ.get('REVIEW_URL') else page.set_content(html,wait_until='domcontentloaded',timeout=15000);page.wait_for_timeout(1700)
 page.evaluate('(g)=>{document.querySelectorAll("dialog[open]").forEach(d=>d.close());GomokuStudio.importGame(g);}',fixture)
 original=page.evaluate('GomokuStudio.exportGame()')
 check('full app, including all course scripts, imports without observer deadlock')
 page.evaluate('document.getElementById("resultReviewBtn").click()');page.wait_for_function('GomokuReview.state()?.results.every(Boolean) && !GomokuReview.state().scanning',timeout=30000)
 s=state(page);check('post-game button opens one guided review, evaluates both colors',len(s['results'])==10 and len(page.locator('dialog[open]').all())==1)
 check('correct actual move coordinate K7',s['results'][4]['played']==129 and 'K7' in s['results'][4]['explanation']['why'])
 check('decisive mistake is identified',s['results'][6]['label']=='Blunder')
 check('later forced loss is not blamed again',s['results'][8]['label']=='Already lost')
 check('opponent winning threat and win are evaluated',s['results'][7]['label']=='Winning threat' and s['results'][9]['label']=='Winning move')
 page.evaluate('GomokuReview.select(7)');page.screenshot(path=str(OUT/'01-desktop-review.png'))
 (OUT/'result.json').write_text(json.dumps(s,indent=2))
 check('previous/next controls visible without losing board',page.locator('#grNext').is_visible())
 check('export and safety note remain reachable',page.locator('#grExport').is_visible())
 page.locator('#grBefore').click();check('before view removes played stone',page.locator('[data-point="111"]').get_attribute('data-stone')=='0')
 page.locator('#grPlayed').click();check('played view restores original stone',page.locator('[data-point="111"]').get_attribute('data-stone')=='1')
 page.locator('#grBest').click();s=state(page);check('show best creates separate variation',s['mode']=='explore' and len(s['branch']['moves'])==1)
 page.screenshot(path=str(OUT/'02-variation.png'))
 page.locator('#grReply').click();page.wait_for_function('!GomokuReview.state().interacting',timeout=10000);check('engine can play reply in sandbox',len(state(page)['branch']['moves'])==2)
 page.locator('#grUndo').click();check('undo changes only variation',len(state(page)['branch']['moves'])==1)
 page.locator('#grReturn').click();check('one-click return restores selected game move',state(page)['mode']=='game' and state(page)['index']==6)
 page.locator('#grRetry').click();check('retry hides answer and alternatives',page.locator('#grVerdict').inner_text()=='Find your move' and page.locator('[data-alternative]').count()==0)
 best=state(page)['results'][6]['best'];page.locator(f'[data-point="{best}"]').click();page.wait_for_function('!!GomokuReview.state().attempt?.result',timeout=12000);s=state(page);check('retry is independently analyzed, not exact-match grading',s['attempt']['result']['played']==best and s['attempt']['result']['budget']==1000)
 page.screenshot(path=str(OUT/'03-retry-feedback.png'))
 page.locator('#grReturn').click();page.evaluate('GomokuReview.select(10)');page.locator('#grBest').click();check('winning variation stops legal continuation','wins' in page.locator('#grBoardTitle').inner_text() and page.locator('#grReply').is_disabled())
 page.locator('#grReturn').click();page.evaluate('GomokuReview.select(5)');page.locator('#grExplore').click();page.locator('[data-point="96"]').click();page.wait_for_function('!GomokuReview.state().interacting',timeout=10000)
 page.evaluate('document.getElementById("grReply").click();document.getElementById("grUndo").click()');page.wait_for_function('!GomokuReview.state().interacting',timeout=10000);check('undo rejects stale async reply',len(state(page)['branch']['moves'])==0)
 page.locator('#grReturn').click();page.locator('#grDeeper').click();page.wait_for_function('!GomokuReview.state().interacting',timeout=15000);check('deeper analysis replaces selected evidence',state(page)['results'][4]['budget']==2400)
 page.locator('#grFilter').select_option('mine');check('your-moves filter excludes opponent',page.locator('[data-review-ply]').count()>=5 and page.locator('#grMoveList .gr-record-move').count()==5)
 page.locator('#grFilter').select_option('mistakes');check('key moment filter exposes actionable mistakes',page.locator('#grMoveList .gr-record-move').count()>0)
 page.locator('[data-point="112"]').focus();page.keyboard.press('ArrowRight');check('board supports coordinate keyboard navigation',page.evaluate('document.activeElement.dataset.point')=='113')
 check('recorded game and study tree unchanged',page.evaluate('GomokuStudio.exportGame().moves')==original['moves'] and page.evaluate('GomokuStudio.exportGame().studio.tree')==original['studio']['tree'])
 data=page.evaluate("""async()=>{const old=URL.createObjectURL,click=HTMLAnchorElement.prototype.click;let blob;URL.createObjectURL=b=>{blob=b;return old(b)};HTMLAnchorElement.prototype.click=()=>{};try{GomokuReview.exportReview();return JSON.parse(await blob.text())}finally{URL.createObjectURL=old;HTMLAnchorElement.prototype.click=click}}""")
 (OUT/'exported-review.json').write_text(json.dumps(data,indent=2));check('export payload preserves game, judgments and variations',len(data['results'])==10 and len(data['variations'])>0 and data['game']['moves']==original['moves'])
 for width in [390,360,768]:
  page.set_viewport_size({'width':width,'height':844 if width<500 else 1024});page.evaluate('GomokuReview.select(7)');page.wait_for_timeout(100)
  dims=page.evaluate('(()=>{const d=document.getElementById("grDialog"),c=d.querySelector(".gr-content");return [d.scrollWidth,d.clientWidth,c.scrollWidth,c.clientWidth]})()')
  check(f'{width}px viewport has no horizontal overflow',dims[0]<=dims[1]+1 and dims[2]<=dims[3]+1)
  page.screenshot(path=str(OUT/f'04-responsive-{width}.png'))
 page.set_viewport_size({'width':1440,'height':1000});page.evaluate('document.body.dataset.theme="dark"');page.screenshot(path=str(OUT/'05-dark.png'));page.evaluate('document.body.dataset.theme="paper"')
 page.keyboard.press('Escape');check('Escape exits cleanly',not page.locator('#grDialog').is_visible() and state(page) is None)
 # Restart without cached results; pause cancels the worker immediately.
 page.evaluate('try{localStorage.removeItem("gomoku.guided-review.v1")}catch{}')
 page.evaluate('GomokuReview.open();document.getElementById("grPause").click()');page.wait_for_timeout(200)
 check('pause cancels in-flight analysis',not state(page)['scanning'] and not state(page)['interacting'])
 page.locator('#grPause').click();page.wait_for_function('GomokuReview.state().results.every(Boolean)&&!GomokuReview.state().scanning',timeout=30000);check('resume completes remaining decisions')
 check('no uncaught browser errors',not errors)
 (OUT/'browser-report.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'pageErrors':errors,'origin':os.environ.get('REVIEW_URL','set_content'),'scope':'Full inline application, synthetic fixture, Chromium. Navigation uses REVIEW_URL when provided; otherwise set_content. Not physical-device or all-browser certification.'},indent=2))
 b.close()
print(f'{len(checks)} browser checks passed',flush=True)
