export function createEngine(variant='renju-practice') {
  if(!['renju-practice','exact-five','freestyle'].includes(variant)) throw new Error('Unknown ruleset.');
  const renju=variant==='renju-practice';
  const exact=color=>variant==='exact-five'||(renju&&color===1);
  const N=15,CELLS=225,BLACK=1,WHITE=2;
  const DIRS=[[1,0],[0,1],[1,1],[1,-1]];
  const inside=(x,y)=>x>=0&&y>=0&&x<N&&y<N;
  const axes=Array.from({length:CELLS},()=>[]);
  for(let d=0;d<DIRS.length;d++){const [dx,dy]=DIRS[d];for(let y=0;y<N;y++)for(let x=0;x<N;x++){if(inside(x-dx,y-dy))continue;const cells=[];for(let xx=x,yy=y;inside(xx,yy);xx+=dx,yy+=dy)cells.push(yy*N+xx);cells.forEach((i,p)=>{axes[i][d]={cells,p,d};});}}
  const invalid=reason=>({legal:false,win:false,foul:false,reason,fours:[],threes:[],winLines:[]});
  function runs(board,i,color){return axes[i].map(({cells,p})=>{let l=p,r=p;while(l>0&&board[cells[l-1]]===color)l--;while(r+1<cells.length&&board[cells[r+1]]===color)r++;return cells.slice(l,r+1);});}
  function fourGroups(board,i,color){const groups=new Map();for(const {cells,p,d} of axes[i])for(let s=Math.max(0,p-4);s<=Math.min(p,cells.length-5);s++){const stones=[];let empty=-1,blocked=false;for(let k=s;k<s+5;k++){const j=cells[k],v=board[j];if(v===color)stones.push(j);else if(v!==0||empty!==-1){blocked=true;break;}else empty=j;}if(blocked||stones.length!==4||empty<0)continue;if(exact(color)&&((s>0&&board[cells[s-1]]===color)||(s+5<cells.length&&board[cells[s+5]]===color)))continue;const key=d+':'+stones.join(',');if(!groups.has(key))groups.set(key,{stones,ends:[],d});const g=groups.get(key);if(!g.ends.includes(empty))g.ends.push(empty);}return [...groups.values()].map(g=>({...g,straight:g.ends.length===2}));}
  function possibleThrees(board,i,color){const groups=new Map();for(const {cells,p,d} of axes[i])for(let s=Math.max(1,p-3);s<=Math.min(p,cells.length-5);s++){if(board[cells[s-1]]!==0||board[cells[s+4]]!==0)continue;if(exact(color)&&((s>1&&board[cells[s-2]]===color)||(s+5<cells.length&&board[cells[s+5]]===color)))continue;const stones=[];let extension=-1,blocked=false;for(let k=s;k<s+4;k++){const j=cells[k],v=board[j];if(v===color)stones.push(j);else if(v!==0||extension!==-1){blocked=true;break;}else extension=j;}if(blocked||stones.length!==3||extension<0)continue;const key=d+':'+stones.join(',');if(!groups.has(key))groups.set(key,{stones,extensions:[],d});groups.get(key).extensions.push(extension);}return [...groups.values()];}
  function inspect(board,i,color,memo){const rr=runs(board,i,color),winLines=rr.filter(a=>exact(color)?a.length===5:a.length>=5);if(winLines.length)return {legal:true,win:true,foul:false,reason:'five',fours:[],threes:[],winLines};if(renju&&color===BLACK&&rr.some(a=>a.length>5))return {legal:false,win:false,foul:true,reason:'overline',fours:[],threes:[],winLines:[]};const fours=fourGroups(board,i,color);if(renju&&color===BLACK&&fours.length>=2)return {legal:false,win:false,foul:true,reason:'double-four',fours,threes:[],winLines:[]};const threes=[];for(const group of possibleThrees(board,i,color)){const legalExtensions=[];for(const e of group.extensions){let a;if(renju&&color===BLACK){const key=board.join('')+':'+e;a=memo.get(key);if(!a){board[e]=color;try{a=inspect(board,e,color,memo);}finally{board[e]=0;}memo.set(key,a);}}else{board[e]=color;try{a={legal:true,win:runs(board,e,color).some(r=>exact(color)?r.length===5:r.length>=5)};}finally{board[e]=0;}}if(a.legal&&!a.win)legalExtensions.push(e);}if(legalExtensions.length)threes.push({...group,extensions:legalExtensions});}const foul=renju&&color===BLACK&&threes.length>=2;return {legal:!foul,win:false,foul,reason:foul?'double-three':'legal',fours,threes,winLines:[]};}
  function classify(board,i,color){if(!board||board.length!==CELLS||!Number.isInteger(i)||i<0||i>=CELLS||(color!==BLACK&&color!==WHITE))return invalid('invalid');if(board[i]!==0)return invalid('occupied');board[i]=color;try{return inspect(board,i,color,new Map());}finally{board[i]=0;}}
  function legalMove(board,i,color,moveCount){if(i===-1)return moveCount>=3?{legal:true,win:false,foul:false,reason:'pass',fours:[],threes:[],winLines:[]}:invalid('opening-pass');return classify(board,i,color);}
  return {N,CELLS,BLACK,WHITE,classify,legalMove,variant};
}
